[terminal.shell]
program = "wsl"
args = [
    "--distribution", "ArchLinux",
    "--cd", "~",
    "-- tmux"
]

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 9

# [general]
# import = [
#     "~/appdata/roaming/alacritty/catppuccin-mocha.toml",
#     "~/.config/dotfiles/alacritty/catppuccin-mocha.toml"
# ]
